# Generated by Django 5.0.2 on 2024-03-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_category_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='old_c',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
