# Generated by Django 5.0.2 on 2024-04-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_old_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='outsidelink',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
