# Generated by Django 5.0.2 on 2024-04-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_outsidelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Nic',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
