# Generated by Django 5.0.2 on 2024-05-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_p_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_img',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=250, null=True, upload_to=''),
        ),
    ]
