# Generated by Django 5.0.2 on 2024-05-05 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_p_img_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_img',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productimages', to='store.product'),
        ),
    ]
