# Generated by Django 4.2.7 on 2023-12-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/product/'),
        ),
    ]
